#!/usr/bin/env python3
"""Regenerate crates/save/src/palette.rs from the game's own colour DataTables.

The character creator's swatch palettes live in these DataTables (all under
Content/ROD/DataAssets/... in the game paks):

  DT_AvatarCustomizeSkinColorPallet      skin   (Main = face highlight layer,
                                                 Sub  = body skin / face base)
  DT_AvatarCustomizePalletData           hair   (shared by hair / eyebrow / beard)
  DT_AvatarCustomizeEyeColorPallet       eye    (Main = iris base, Sub = bright ring)
  DT_AvatarCustomizeEyePointColorPallet  eye point
  DT_AvatarCustomizeEyelineColorPallet   eyeline
  DT_AvatarCustomizeLipColorPallet       lip
  DT_CostumeColorList                    costume channel colours

Dump them to JSON with eoadump (eoa-weapon-kit/tools/eoadump), then run this:

  eoadump "<Paks dir>" <dump-dir> 'DT_(AvatarCustomize(EyeColor|EyelineColor|EyePointColor|LipColor|SkinColor)Pallet|AvatarCustomizePalletData|CostumeColorList)\\.uasset'
  python3 scripts/extract-palettes.py <dump-dir>

Rows are ordered by their ID column (the creator's display order). Every
51-row table carries a leftover `NewRow` dev entry that duplicates ID 0 —
it is dropped (the game indexes rows by ID, so it is shadowed anyway).
"""

import json
import pathlib
import sys

TABLES = [
    # (json name, rust static name)
    ("DT_AvatarCustomizeSkinColorPallet", "SKIN"),
    ("DT_AvatarCustomizePalletData", "HAIR"),
    ("DT_AvatarCustomizeEyeColorPallet", "EYE"),
    ("DT_AvatarCustomizeEyePointColorPallet", "EYE_POINT"),
    ("DT_AvatarCustomizeEyelineColorPallet", "EYELINE"),
    ("DT_AvatarCustomizeLipColorPallet", "LIP"),
    ("DT_CostumeColorList", "COSTUME"),
]

HEADER = '''\
//! The character creator's own colour palettes, extracted verbatim from the
//! game's DataTables so the editor can offer "match the game" swatches next to
//! the free colour pickers.
//!
//! GENERATED by scripts/extract-palettes.py — edit that script, not this file.
//!
//! Layer semantics (verified against a creator-made save, 2026-07-23):
//! - Skin pick N writes `CustomColorSkin` = Sub, `CustomColorFaceG` = Sub
//!   (face base = body skin) and `CustomColorFaceR` = Main (face highlight).
//! - Eye pick N writes `CustomColorPupilR` = Main (iris base) and
//!   `CustomColorPupilG` = Sub (bright ring).
//! - Hair pick writes Main to `CustomColorHairR` only (HairG/HairB are
//!   mesh-specific extra layers the creator leaves alone).
//! - Every other palette has Main == Sub (single-colour rows).

/// One creator swatch: the DataTable row name plus its two colour layers
/// (`main == sub` for the single-layer palettes).
pub struct Swatch {
    pub name: &'static str,
    pub main: [f32; 3],
    pub sub: [f32; 3],
}
'''

FOOTER = '''
/// The creator palette offered for a save colour field, or `None` when the
/// game has no palette for it. Eyebrow (`CustomColorFaceB`) and the extra
/// hair layers share the hair palette — same family in the creator.
pub fn palette_for(field: &str) -> Option<&'static [Swatch]> {
    Some(match field {
        "CustomColorSkin" | "CustomColorFaceR" | "CustomColorFaceG" => SKIN,
        "CustomColorHairR" | "CustomColorHairG" | "CustomColorHairB" | "CustomColorFaceB"
        | "CustomColorBeard" => HAIR,
        "CustomColorPupilR" | "CustomColorPupilG" => EYE,
        "CustomColorPupilB" => EYE_POINT,
        "CustomColorEye" => EYELINE,
        "CustomColorLip" => LIP,
        n if n.starts_with("Upper") || n.starts_with("Gloves") || n.starts_with("Lower") => COSTUME,
        _ => return None,
    })
}

/// The writes a swatch click performs, mirroring the creator's layer wiring:
/// picking a skin tone re-tints the face layers with it (exactly like the
/// creator — and like the editor's existing skin→face sync, but exact instead
/// of delta-based); every other field takes the layer that belongs to it.
pub fn swatch_writes(field: &str, s: &Swatch) -> Vec<(String, [f32; 4])> {
    let rgba = |c: [f32; 3]| [c[0], c[1], c[2], 1.0];
    match field {
        "CustomColorSkin" => vec![
            ("CustomColorSkin".into(), rgba(s.sub)),
            ("CustomColorFaceG".into(), rgba(s.sub)),
            ("CustomColorFaceR".into(), rgba(s.main)),
        ],
        // Sub-layer fields: the creator writes the row's SubColor here.
        "CustomColorFaceG" | "CustomColorPupilG" => vec![(field.into(), rgba(s.sub))],
        _ => vec![(field.into(), rgba(s.main))],
    }
}
'''


def main() -> None:
    dump = pathlib.Path(sys.argv[1])
    out = [HEADER]
    for json_name, rust_name in TABLES:
        rows = json.loads((dump / f"{json_name}.json").read_text())[0]["Rows"]
        ordered = sorted(
            ((r.get("ID", 0), name, r) for name, r in rows.items() if name != "NewRow"),
            key=lambda t: t[0],
        )
        out.append(f"\n/// {json_name} ({len(ordered)} rows).")
        out.append(f"pub static {rust_name}: &[Swatch] = &[")
        for _, name, r in ordered:
            if "MainColor" in r:
                main = r["MainColor"]
                sub = r["SubColor"]
            else:  # DT_CostumeColorList: single Color column
                main = sub = r["Color"]
            m = ", ".join(repr(float(main[c])) for c in "RGB")
            sv = ", ".join(repr(float(sub[c])) for c in "RGB")
            out.append(
                f'    Swatch {{ name: "{name}", main: [{m}], sub: [{sv}] }},'
            )
        out.append("];")
    out.append(FOOTER)
    target = pathlib.Path(__file__).resolve().parent.parent / "crates/save/src/palette.rs"
    target.write_text("\n".join(out))
    print(f"wrote {target}")


if __name__ == "__main__":
    main()
